# Site settings
title: "无声的纪念"
email: 6-4@tuta.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://6-4.github.io" # the base hostname & protocol for your site

twitter_username: "__64__"
github_username: 6-4

# Build settings
markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass
